version: "3"
services:
  server:
    container_name: backendAPI
    image: "demobackend"
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./sampleData/localdata:/srv/app/images
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
